### ISSUE TITLE
Update pages of lightning talks

### ISSUE THREAD

**Issue by nomoregrapes** [openstreetmap/stateofthemap-2018#102]
I've been able to create new pages for the lightning talks, e.g. [LX01], but it is not listed on the list of lightning talks block 3, and I don't understand how/where to update that.

Some didn't seem to take place (as we don't have videos). I've marked these "remove?" but we should possibly keep them, just for information on what was scheduled.

If someone could do it, then this is what needs to be listed:

* [LT Block 1](https://2018.stateofthemap.org/lightning_talks/lightning_talks_1/)
  * all okay, no changes
* [LT 2](https://2018.stateofthemap.org/lightning_talks/lightning_talks_2/)
  * Title should state `Lightning talks on Sunday 10:00 in De Donato`
  * No change to list
* [LT 3](https://2018.stateofthemap.org/lightning_talks/lightning_talks_3/)
  * LX01-My_message_in_weeklyOSM
  * LX02-SOTM_Asia_2018
  * L047 (keep)
  * L041 (keep)
* [LT 4](https://2018.stateofthemap.org/lightning_talks/lightning_talks_4/)
  * No changes
* [LT 5](https://2018.stateofthemap.org/lightning_talks/lightning_talks_5/)
  * L046 (keep)
  * L029 (keep)
  * L021 (keep)
  * L017 (remove?)
  * LX03-Blockchain_and_OSM
* [LT 6](https://2018.stateofthemap.org/lightning_talks/lightning_talks_6/)
  * L040 (remove?)
  * L026 (keep)
  * L018 (keep)
  * L002 (keep)
  * LX04-OSM_and_Blender
* [LT 7](https://2018.stateofthemap.org/lightning_talks/lightning_talks_7/)
  * L051 (keep)
  * L048 (move to LT9) - I think this got postponed & ended up in S.1.5(unfilmed) the following day)
  * L034 (keep)
  * L014 (keep)
* [LT 8](https://2018.stateofthemap.org/lightning_talks/lightning_talks_8/)
  * Not filmed, LX05 to LX08 pages exist.
* LT 9
  * Not filmed, LX09 to LX11 pages exist
  * Could add L048 at the end.
* LT 10
  * Not filmed, LX12 to LX15 pages exist.

**Comment by Firefishy** [comment]
Closing due to age. Feel free to re-open if still relevant.
