### ISSUE TITLE
decorate attributions with icons and links

### ISSUE THREAD

**Issue by althio** [openstreetmap/stateofthemap-2018#17]
Do you think we could squeeze more into the attribution, with icons and links?

A few proposals or tests:
### [Map data](https://www.openstreetmap.org/about) [© OpenStreetMap contributors](https://www.openstreetmap.org/copyright)   [🔧](https://www.openstreetmap.org/fixthemap) [❤️](https://donate.openstreetmap.org) [🗺](https://join.osmfoundation.org) 

```
<a href="https://www.openstreetmap.org/about" target="_blank">Map data</a> 
<a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap contributors</a>   
<a href="https://www.openstreetmap.org/fixthemap" target="_blank"fix</a> 
<a href="https://donate.openstreetmap.org" target="_blank">heart</a> 
<!-- see https://donate.openstreetmap.org/img/favicon.png -->
<a href="https://join.osmfoundation.org" target="_blank">join/world/map/osm</a>
```
 
follows https://github.com/osmfoundation/sotm2018/issues/36 😉

**Comment by frafra** [comment]
Thank you @althio :)
I just upgraded to the latest version of font-awesome and added your code.
