### ISSUE TITLE
Social media buttons

### ISSUE THREAD

**Issue by frafra** [openstreetmap/stateofthemap-2018#19]
They are currently missing :)

**Comment by frafra** [comment]
Do we have social pages/profiles on Facebook or other social networks?

**Comment by althio** [comment]
> Do we have social pages/profiles on Facebook or other social networks?

You already have [twitter](https://twitter.com/sotm) and [wiki](https://wiki.openstreetmap.org/wiki/State_of_the_Map_2018) 
Another link to the newsletter signup maybe?
A direct email address?
I think that's all for SotM.

for OSM(F):
https://www.facebook.com/OpenStreetMap/
https://blog.openstreetmap.org/

**Comment by RobJN** [comment]
>A direct email address?
team@stateofthemap.org

I also add youtube (from previous SotM) to the email newsletter:
https://www.youtube.com/channel/UC0jDNhn6t-PLVvqMPL-ZWbg

**Comment by frafra** [comment]
We could move the code of conduct on the first column and add the OSM(F) links to the right column if you agree.

**Comment by RobJN** [comment]
> We could move the code of conduct on the first column and add the OSM(F) links to the right column if you agree.

Makes sense 👍

**Comment by frafra** [comment]
Feel free to reopen this issue if you think something is missing :)
