### ISSUE TITLE
add call for proposals to website

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2018#20]
email has already gone out. will post to blog soon. add text and link on website to submit proposals

**Comment by frafra** [comment]
Fixed, thank @mikelmaron. I used flags for the language selector instead of text, in order to make the navbar more compact and avoid buttons over multiple lines on medium-sized screens.

**Comment by frafra** [comment]
I also added it to the wiki page on the right column: https://wiki.openstreetmap.org/wiki/State_of_the_Map_2018
