### ISSUE TITLE
change the website to welcome the call for abstracts for the Academic Track

### ISSUE THREAD

**Issue by MarcoMinghini** [openstreetmap/stateofthemap-2018#22]
I propose the following edits to the current website:
1) clicking on "Call for proposals", a new page opens explaining that there are different calls: standard presentations, Academic presentations, and workshops.
2) Then, in the same page or in another one, you can copy-paste the call for the Academic Track - provisional text (still to be finalized) available at https://docs.google.com/document/d/1VE1EdIJP19uNTcqVORcWSdpejd15h4i0cPw9rmGWvNc/edit?usp=sharing

I will provide the tinal text once this is finalized.

**Comment by frafra** [comment]
I agree, we should have a single page with two different sections.

**Comment by MarcoMinghini** [comment]
> I agree, we should have a single page with two different sections. >

Now two different sections, then we'll have a third section (workshops).

**Comment by frafra** [comment]
Sorry, I was thinking about having a single page for call for proposals/academic abstracts. Workshop can be placed on the same page too.

We have little space on the main menu; so we should use a different name.

We should also think about if we want to have scholarships shown on the homepage only.

**Comment by frafra** [comment]
Very short text at the moment:

- en: https://github.com/openstreetmap/stateofthemap-2018/blob/call-for-proposals-page/callforproposals/index.md
- it: https://github.com/openstreetmap/stateofthemap-2018/blob/call-for-proposals-page/it/callforproposals/index.md
