### ISSUE TITLE
updates for closing calls

### ISSUE THREAD

**Issue by althio** [openstreetmap/stateofthemap-2018#38]
- [x] close main call
- [x] close academic call
- [x] close scholarship call
- [x] announce poster call
- [x] announce community survey

**Comment by RobJN** [comment]
@frafra do you have time to do these updates soon? All but the poster call can be done now.

**Comment by frafra** [comment]
Sorry @RobJN and sorry to everybody, I was busy and I am fixing everything :)

**Comment by frafra** [comment]
Poster call added, issue is now close :)
