### ISSUE TITLE
Add logos of first few sponsors

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#39]
Hi @frafra. We have our first few sponsors:
![image](https://user-images.githubusercontent.com/5060210/37000753-378a4a00-20bc-11e8-99f0-9d7c738cb556.png)

Can you please add their logos to the front page.

**Comment by RobJN** [comment]
You can copy and past from last year's website:
https://github.com/openstreetmap/stateofthemap-2017/blob/gh-pages/_includes/sponsors.html

We need a logo for OSMAnd. I shall ask for that now.

**Comment by RobJN** [comment]
![logo-osmand-black](https://user-images.githubusercontent.com/5060210/37001145-7a2abce0-20bd-11e8-88fc-c3300d0324fd.png)

**Comment by frafra** [comment]
I had to invert the OsmAnd logo colors (from black to white).
