### ISSUE TITLE
Add link to poster competion

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#49]
Hi @frafra 

Do you have any time to update the website with the poster competition link? This can be found here:
https://blog.openstreetmap.org/2018/04/23/participate-in-our-poster-competition/

Note: We are also ready for the program to be added online. We now have the help of @Nakaner. Is it ok if I leave it to you two to work out how best to split your time? I'm keen that we get the website updated, but the SotM site is also quite a good place to learn a new skill. So _if_ there is an opportunity to learn of each other, feel free to do this even if it slows us down a little bit. If not, then as soon as you have spare time :smiley:

**Comment by frafra** [comment]
Sure, I have time this week to work on it and I would be glad to work together with @Nakaner, even if this could require a bit more time, because I agree that this could be a good opportunity to learn something new and growth as community :)

**Comment by frafra** [comment]
I was waiting for the announcement for closing issue no. #38 ;)
I am closing this bug, but feel free to give my personal information to @Nakaner in order to keep in touch :)
