### ISSUE TITLE
Sponsor logos - round 2

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#50]
Hi @frafra:

We need some more logos adding to the website please. Details are:

Bing = Gold
Mapbox = Gold
Garmin = Bronze
KAART = Bronze

Logos already exist for the top two in: https://github.com/openstreetmap/stateofthemap-2018/tree/gh-pages/logos

I will source the others.

**Comment by RobJN** [comment]
Garmin logo: (White on white sucks - I promise it is there):

![garmin](https://user-images.githubusercontent.com/5060210/39154883-cda8922e-4747-11e8-9ea8-1a6cb2c24449.png)

**Comment by frafra** [comment]
Thank you Rob; do we have a logo for KAART?

**Comment by RobJN** [comment]
Just got it. Again white on white. I had to convert this from JPG from their facebook page so hopefully it looks ok. If problematic I can have another go.

Logo is here:
![kaart](https://user-images.githubusercontent.com/5060210/39155966-263e85b6-474c-11e8-8662-86eb42fcac5d.png)

**Comment by frafra** [comment]
It is not the best solution, but it works; thank you :)

**Comment by RobJN** [comment]
Am seeing if I can do a conversion to SVG to get better results. Don't let me stop you doing a first update though.

**Comment by RobJN** [comment]
I think this is better for KAART:
![kaartsvg](https://user-images.githubusercontent.com/5060210/39156373-beb6d6b2-474d-11e8-8199-03c478d4a81d.png)
