### ISSUE TITLE
Changing background

### ISSUE THREAD

**Issue by frafra** [openstreetmap/stateofthemap-2018#51]
Hi @RobJN,
I remember we talk about changing the background from time to time.
We can choose to pick them from the Google Drive folder we prepared or to use a service like https://unsplash.com/search/photos/milan

What do you think about it?

**Comment by RobJN** [comment]
Can do. Ensuring a continuous "visual brand" might be harder tough. Are there other options such as use of images in places other than the main header image?

**Comment by frafra** [comment]
Mmm... A carousel maybe?

**Comment by frafra** [comment]
Outdated.
