### ISSUE TITLE
Build warning - CNAME

### ISSUE THREAD

**Issue by frafra** [openstreetmap/stateofthemap-2018#53]
I always receive this message in my mailbox:

```
The page build completed successfully, but returned the following warning for the `gh-pages` branch:

Your site's DNS settings are using a custom subdomain, 2018.stateofthemap.org, that's set up as an A record. We recommend you change this to a CNAME record pointing at openstreetmap.github.io. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

```

As we use a custom server, I think we can remove the CNAME file from this repository; we do not need GitHub pages for this project.

**Comment by RobJN** [comment]
This occurred when the site was switched to HTTPS. @tomhughes may be able to switch it to CNAME as suggested in the warning above. It is working as is though, just spawning this message.

**Comment by tomhughes** [comment]
Um. You realise it's not running on github pages right? The A record points at one of our servers!

**Comment by RobJN** [comment]
Yes, I understand that there is some form of replication to our servers. 

Confirmation of a right course of action much appreciated. Is it to remove the CNAME file from this repo as FraFra suggested, or something else?

I think I've talked myself into believing that is the right action but hosting sites is not my area of expertise and is rather not break anything!

**Comment by tomhughes** [comment]
Yes, if you're only building it for gh pages so that you can view it through the github.io link then you don't need that file.
