### ISSUE TITLE
Add Immobilaire logo as Silver sponsor

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#71]
Hi @frafra. This logo needs adding. It is attached below (white text on white background on GitHub web portal).
![immobilaire](https://user-images.githubusercontent.com/5060210/42188431-c34a91d4-7e4b-11e8-8a41-8d1c17d41222.png)

**Comment by RobJN** [comment]
This logo isn't showing on my laptop on 2018.stateofthemap.org following @frafra's edit. Can you check it again please. Thanks.
 (cc @Nakaner).

**Comment by frafra** [comment]
Uhm... I think that the sotm build system is broken. I checked locally, cleaned up caches, and it works.

**Comment by RobJN** [comment]
> Uhm... I think that the sotm build system is broken.

Does this mean we need @tomhughes to help us again?

**Comment by tomhughes** [comment]
Should be fixed now.

**Comment by RobJN** [comment]
Perfect - thanks.
