### ISSUE TITLE
Promote the SotM Android app on the homepage

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/stateofthemap-2018#85]
Some home page publicity is needed here. App is at:

https://2018.stateofthemap.org/sotm.apk

**Comment by althio** [comment]
Also could be added:
- Twitter hashtag #sotm and our account @sotm
- public Telegram group, join link

**Comment by RobJN** [comment]
First attempt via #89. This is the best I can do with my skil-lset. I expect there is a much better and more visual option so feel free to amend. Maybe @harry-wood could take a look if not travelling.

**Comment by harry-wood** [comment]
It looks alright to me.

A general thought I would have though, is maybe that section should be about the "program" (to bring more prominence to that juicy info onto the front page) with a small link to the android app download. 
Could link it the android app again bigger with something more visual on program page.

Probably already discussed, but did anyone try publishing the app on the google play store? I could be wrong, but I thought an APK download link doesn't actually work unless you disable a security setting (arguably for very good reasons)

**Comment by RobJN** [comment]
> Probably already discussed, but did anyone try publishing the app on the google play store?

Do you know of an OSMF google account to publish from?

**Comment by harry-wood** [comment]
hmm. We probably do. I mean we've got various google things. We definitely have an "osmfoundation"  "organisation" for using google docs for example. The OWG folks will know I suppose.

I'm not sure how easy this is. Publishing an iOS app is super complicated and slow, but maybe an android app could be published in time for the conference if somebody knew what they were doing.
